/*
 * Archivo de convenciones comunes con Kotlin, Spotless y JaCoCo
 */

plugins {
    id 'org.jetbrains.kotlin.jvm'
    id 'com.diffplug.spotless'
    id 'jacoco'
    id 'maven-publish'
}

repositories {
    mavenCentral()
}

dependencies {
    constraints {
        implementation 'org.apache.commons:commons-text:1.12.0'
    }

    testImplementation 'org.junit.jupiter:junit-jupiter:5.11.3'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

// Toolchain para Java
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

spotless {
    kotlin {
        target '**/*.kt'
        targetExclude '**/build/**'
        ktlint('0.50.0')
    }
    kotlinGradle {
        target '**/*.kts'
        ktlint()
    }
}

tasks.named('test') {
    useJUnitPlatform()
    finalizedBy tasks.jacocoTestReport
}

jacocoTestReport {
    dependsOn test
    reports {
        xml.required = true
        html.required = true
    }
}

jacocoTestCoverageVerification {
    dependsOn test
    violationRules {
        rule {
            limit {
                minimum = 0.65
            }
        }
    }
}

tasks.named('check') {
    dependsOn 'spotlessCheck', 'jacocoTestCoverageVerification'
}

tasks.named('build') {
    dependsOn 'spotlessApply'
}
group = "com.JVM-austral"
version = "1.0.0-SNAPSHOT"

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }

    repositories {
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/JVM-austral/tp-ingsis-interpreter") // reemplaza OWNER/REPO
            credentials {
                username = project.findProperty("gpr.user") ?: System.getenv("GITHUB_ACTOR")
                password = project.findProperty("gpr.token") ?: System.getenv("GITHUB_TOKEN")
            }
        }
    }
}
